name: Release
on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          compiler: latexmk
          latexmk_use_xelatex: true
          args: -jobname=beer-algebra -pdf -file-line-error -halt-on-error -interaction=nonstopmode
          post_compile: "latexmk -c"
          extra_fonts: ./resources/fonts/*.ttf
  
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: softprops/action-gh-release@v1
        with:
          files: beer-algebra.pdf

  upload:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      # - run: mkdir -p path/to/artifact
      # - run: echo hello > path/to/artifact/world.txt
      - uses: actions/upload-artifact@v3
        with:
          name: beer-algebra.pdf
          path: .
