name: Release
on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          compiler: latexmk
          latexmk_use_xelatex: true
          args: -jobname=beer-algebra -pdf -file-line-error -halt-on-error -interaction=nonstopmode
          post_compile: "latexmk -c"
          extra_fonts: ./resources/fonts/*.ttf
  
  upload:
    runs-on: ubuntu-latest
    permissions: write
    needs: [build]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/upload-artifact@v3
      with:
        name: beer-algebra
        path: ./beer-algebra.pdf
